run:
  deadline: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  formats:
    - github-actions

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 50
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/aymaneallaoui/zod-go
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/aymaneallaoui/zod-go/zod
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
    enabled-checks:
      - builtinShadow
  funlen:
    lines: 80
    statements: 40
  gocognit:
    min-complexity: 20

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - gochecknoglobals # too strict for this project
    - lll
    - maligned # remove this
    - scopelint # replace with exportloopref
    - gomnd # use mnd
    - structcheck # use unused
    - varcheck # use unused
    - golint # use revive
    - interfacer # deprecated
    - deadcode # use unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - dupl
    - linters:
        - lll
      source: "^//go:generate "
  exclude:
    - "exported .* should have comment or be unexported"
    - "should have a package comment"
  exclude-use-default: false
  max-issues-per-linter: 0
  exclude-dirs:
    - examples
  max-same-issues: 0
  new: false
