name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.22" # Specify Go version here

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./tests -v

      - name: Run benchmarks
        run: go test -benchmem -run=^$ -bench . ./benchmarks
